# Generated by Django 6.0.2 on 2026-02-22 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_time_ms', models.IntegerField(help_text='Time taken to generate', null=True)),
                ('total_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'itineraries',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('order', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('travel_time_minutes', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('replanned', 'Replanned')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='User locked - do not replan')),
            ],
            options={
                'db_table': 'itinerary_items',
                'ordering': ['day_number', 'order'],
            },
        ),
    ]
