# Generated by Django 6.0.2 on 2026-02-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
        ('places', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['trip', '-version'], name='itineraries_trip_id_7af422_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['itinerary', 'day_number', 'order'], name='itinerary_i_itinera_4f31bb_idx'),
        ),
    ]
