# Generated by Django 6.0.2 on 2026-02-23 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('rate_from_inr', models.DecimalField(decimal_places=6, help_text='1 INR = X of this currency', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'ordering': ['currency_code'],
            },
        ),
        migrations.CreateModel(
            name='TravelProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('rating', models.FloatField(default=4.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'travel_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'travel_query_cache',
            },
        ),
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], max_length=10)),
                ('provider_name', models.CharField(help_text='Denormalized for speed', max_length=150)),
                ('route_number', models.CharField(blank=True, max_length=30)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_station', models.CharField(blank=True, max_length=200)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_station', models.CharField(blank=True, max_length=200)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('price_inr', models.DecimalField(decimal_places=2, help_text='Price in INR (base currency)', max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stops', models.IntegerField(default=0)),
                ('stop_details', models.JSONField(blank=True, default=list)),
                ('cabin_class', models.CharField(blank=True, help_text='Economy, Business, Sleeper, etc.', max_length=30)),
                ('carbon_kg', models.FloatField(default=0, help_text='Estimated CO2 emissions in kg')),
                ('delay_risk', models.FloatField(default=0.1, help_text='0-1, probability of delay')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_mock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='travel.travelprovider')),
            ],
            options={
                'db_table': 'travel_options',
                'ordering': ['price_inr'],
                'indexes': [models.Index(fields=['departure_city', 'arrival_city', 'departure_time'], name='travel_opti_departu_3fb1f6_idx'), models.Index(fields=['transport_type'], name='travel_opti_transpo_115cb9_idx')],
            },
        ),
    ]
