"""Extended seed data — 10 additional Indian cities (100 places)."""
from places.models import Place, PlaceMetrics

INDIA_PLACES_DATA = [
    # ───────────── CHENNAI (10) ─────────────
    {
        'name': 'Marina Beach',
        'description': 'One of the longest urban beaches in the world stretching over 13 km along the Bay of Bengal.',
        'category': 'relaxation',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0500,
        'longitude': 80.2824,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 0,
        'rating': 4.3,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Kapaleeshwarar Temple',
        'description': 'A stunning 7th-century Dravidian-style Shiva temple in the heart of Mylapore with a 37-metre gopuram.',
        'category': 'culture',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0339,
        'longitude': 80.2698,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.6,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '05:30',
        'closing_hour': '12:00',
        'is_outdoor': False,
    },
    {
        'name': 'Fort St. George',
        'description': 'The first English fortress in India, built in 1644, now housing the Fort Museum and Tamil Nadu Legislature.',
        'category': 'landmark',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0798,
        'longitude': 80.2874,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.2,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Government Museum Chennai',
        'description': 'Second oldest museum in India with an extraordinary bronze gallery of Chola-era sculptures.',
        'category': 'culture',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0694,
        'longitude': 80.2561,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 1,
        'rating': 4.1,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '09:30',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'San Thome Cathedral',
        'description': 'Neo-Gothic cathedral built over the tomb of St Thomas the Apostle, one of only three churches in the world built over an Apostle tomb.',
        'category': 'landmark',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0336,
        'longitude': 80.2782,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.75,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '20:00',
        'is_outdoor': False,
    },
    {
        'name': 'DakshinaChitra Heritage Village',
        'description': 'Living history museum preserving the art, architecture and crafts of South India with 18 authentic homes.',
        'category': 'culture',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 12.7957,
        'longitude': 80.2280,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 3,
        'rating': 4.3,
        'popularity_score': 0.70,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Chettinad Lunch at Ponnusamy',
        'description': 'Legendary Chennai restaurant serving fiery Chettinad chicken, mutton chukka, and traditional banana-leaf meals.',
        'category': 'food',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0472,
        'longitude': 80.2346,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 5,
        'rating': 4.5,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '11:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },
    {
        'name': 'T. Nagar Shopping District',
        'description': 'Bustling commercial hub famous for silk sarees at Nalli and Pothy\'s, gold jewellery, and street food.',
        'category': 'shopping',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0418,
        'longitude': 80.2341,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 15,
        'rating': 4.2,
        'popularity_score': 0.80,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '21:00',
        'is_outdoor': False,
    },
    {
        'name': 'Elliot\'s Beach (Besant Nagar)',
        'description': 'Quieter alternative to Marina Beach, popular with locals for sunrise walks and the Karl Schmidt Memorial.',
        'category': 'relaxation',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 13.0004,
        'longitude': 80.2713,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 0,
        'rating': 4.3,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Covelong Beach Surfing',
        'description': 'Growing surf destination 40 km south of Chennai offering beginner-friendly waves and lessons.',
        'category': 'adventure',
        'city': 'Chennai',
        'country': 'India',
        'latitude': 12.7858,
        'longitude': 80.2520,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 12,
        'rating': 4.4,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '07:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },

    # ───────────── KOLKATA (10) ─────────────
    {
        'name': 'Victoria Memorial',
        'description': 'Magnificent white-marble monument to Queen Victoria, set in 64 acres of lush gardens with a museum inside.',
        'category': 'landmark',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5448,
        'longitude': 88.3426,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 2,
        'rating': 4.6,
        'popularity_score': 0.95,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Howrah Bridge',
        'description': 'Iconic cantilever bridge over the Hooghly River, one of the busiest in the world with 100,000 vehicles daily.',
        'category': 'landmark',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5851,
        'longitude': 88.3468,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.5,
        'popularity_score': 0.92,
        'image_url': '',
        'opening_hour': '00:00',
        'closing_hour': '23:59',
        'is_outdoor': True,
    },
    {
        'name': 'Indian Museum',
        'description': 'The oldest and largest multi-purpose museum in Asia, founded in 1814, with Gandhara sculptures and Egyptian mummies.',
        'category': 'culture',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5580,
        'longitude': 88.3513,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 2,
        'rating': 4.3,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Dakshineswar Kali Temple',
        'description': 'Sacred temple complex dedicated to Goddess Kali, associated with Ramakrishna Paramhansa.',
        'category': 'culture',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.6553,
        'longitude': 88.3575,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 0,
        'rating': 4.7,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '12:30',
        'is_outdoor': False,
    },
    {
        'name': 'Park Street Food Walk',
        'description': 'Kolkata\'s vibrant dining street with iconic restaurants like Peter Cat, Mocambo, and Flurys bakery.',
        'category': 'food',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5515,
        'longitude': 88.3521,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 8,
        'rating': 4.5,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '23:00',
        'is_outdoor': True,
    },
    {
        'name': 'New Market (Hogg Market)',
        'description': 'Victorian-era covered market with over 2,000 stalls selling everything from fabrics to fresh flowers.',
        'category': 'shopping',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5605,
        'longitude': 88.3518,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 10,
        'rating': 4.1,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '20:00',
        'is_outdoor': False,
    },
    {
        'name': 'Marble Palace',
        'description': 'Opulent 19th-century neoclassical mansion with Rubens paintings, Italian marble floors, and a private zoo.',
        'category': 'culture',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5806,
        'longitude': 88.3620,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.2,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '16:00',
        'is_outdoor': False,
    },
    {
        'name': 'Kumortuli Idol-Making Quarter',
        'description': 'Artisan cluster where thousands of clay idols for Durga Puja and other festivals are sculpted by hand.',
        'category': 'culture',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5977,
        'longitude': 88.3618,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Princep Ghat Sunset',
        'description': 'Beautiful riverside promenade along the Hooghly with panoramic sunset views and the Vidyasagar Setu as backdrop.',
        'category': 'relaxation',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.5515,
        'longitude': 88.3350,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.3,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Sundarbans Day Trip',
        'description': 'UNESCO World Heritage mangrove forest — home to Bengal tigers, river dolphins, and over 250 bird species.',
        'category': 'adventure',
        'city': 'Kolkata',
        'country': 'India',
        'latitude': 22.1040,
        'longitude': 88.8723,
        'avg_duration_minutes': 480,
        'avg_cost_usd': 20,
        'rating': 4.6,
        'popularity_score': 0.85,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },

    # ───────────── HYDERABAD (10) ─────────────
    {
        'name': 'Charminar',
        'description': 'Iconic 16th-century monument with four grand arches and a mosque on top, the symbol of Hyderabad.',
        'category': 'landmark',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3616,
        'longitude': 78.4747,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 1,
        'rating': 4.5,
        'popularity_score': 0.94,
        'image_url': '',
        'opening_hour': '09:30',
        'closing_hour': '17:30',
        'is_outdoor': True,
    },
    {
        'name': 'Golconda Fort',
        'description': 'Massive 13th-century fort known for its acoustic architecture — a clap at the entrance can be heard at the top.',
        'category': 'landmark',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3833,
        'longitude': 78.4011,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 2,
        'rating': 4.6,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '17:30',
        'is_outdoor': True,
    },
    {
        'name': 'Ramoji Film City',
        'description': 'World\'s largest integrated film studio complex spread over 1,666 acres with theme parks and guided tours.',
        'category': 'adventure',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.2543,
        'longitude': 78.6808,
        'avg_duration_minutes': 360,
        'avg_cost_usd': 15,
        'rating': 4.3,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:30',
        'is_outdoor': True,
    },
    {
        'name': 'Hussain Sagar Lake',
        'description': 'Heart-shaped lake with a monolithic 18-metre Buddha statue in the centre, accessible by boat.',
        'category': 'nature',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.4239,
        'longitude': 78.4738,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 3,
        'rating': 4.2,
        'popularity_score': 0.80,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Salar Jung Museum',
        'description': 'One of the world\'s largest one-man art collections with 43,000 objects including a Veiled Rebecca sculpture.',
        'category': 'culture',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3714,
        'longitude': 78.4804,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 1,
        'rating': 4.5,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Biryani at Paradise Restaurant',
        'description': 'The legendary home of Hyderabadi Dum Biryani since 1953 — fragrant basmati rice slow-cooked with succulent meat.',
        'category': 'food',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.4410,
        'longitude': 78.4783,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 4,
        'rating': 4.6,
        'popularity_score': 0.92,
        'image_url': '',
        'opening_hour': '11:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },
    {
        'name': 'Chowmahalla Palace',
        'description': 'Grand 18th-century palace of the Nizams with Khilwat Mubarak durbar hall and vintage car collection.',
        'category': 'culture',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3583,
        'longitude': 78.4718,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.4,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Laad Bazaar',
        'description': 'Vibrant old-city market near Charminar famous for lac bangles, pearls, and traditional Hyderabadi perfumes.',
        'category': 'shopping',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3610,
        'longitude': 78.4735,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 8,
        'rating': 4.2,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '10:30',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Birla Mandir Hyderabad',
        'description': 'Gleaming white-marble Hindu temple on Naubath Pahad hill offering panoramic city views.',
        'category': 'culture',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.4065,
        'longitude': 78.4692,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.5,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '07:00',
        'closing_hour': '12:00',
        'is_outdoor': False,
    },
    {
        'name': 'Nehru Zoological Park',
        'description': 'Sprawling 380-acre zoo with lion safari, butterfly garden, and natural habitat enclosures.',
        'category': 'nature',
        'city': 'Hyderabad',
        'country': 'India',
        'latitude': 17.3494,
        'longitude': 78.4517,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 2,
        'rating': 4.1,
        'popularity_score': 0.70,
        'image_url': '',
        'opening_hour': '08:30',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },

    # ───────────── VARANASI (10) ─────────────
    {
        'name': 'Kashi Vishwanath Temple',
        'description': 'One of the holiest Hindu temples dedicated to Lord Shiva, with the new grand corridor completed in 2021.',
        'category': 'culture',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3109,
        'longitude': 83.0107,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 0,
        'rating': 4.8,
        'popularity_score': 0.96,
        'image_url': '',
        'opening_hour': '03:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },
    {
        'name': 'Dashashwamedh Ghat Ganga Aarti',
        'description': 'Mesmerising evening fire ceremony performed on the banks of the Ganges — an unforgettable spiritual experience.',
        'category': 'culture',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3048,
        'longitude': 83.0105,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.9,
        'popularity_score': 0.98,
        'image_url': '',
        'opening_hour': '18:00',
        'closing_hour': '19:30',
        'is_outdoor': True,
    },
    {
        'name': 'Sarnath Buddhist Site',
        'description': 'Where Buddha gave his first sermon — the Dhamek Stupa, Ashoka Pillar ruins, and an archaeological museum.',
        'category': 'culture',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3815,
        'longitude': 83.0224,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 2,
        'rating': 4.5,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Assi Ghat Sunrise',
        'description': 'Southernmost ghat popular with pilgrims and yoga enthusiasts, offering serene morning rituals at dawn.',
        'category': 'relaxation',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.2879,
        'longitude': 83.0041,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '04:30',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Ramnagar Fort',
        'description': '18th-century fort residence of the Maharaja of Benares, housing a museum with vintage cars and royal artefacts.',
        'category': 'landmark',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.2900,
        'longitude': 83.0303,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 1,
        'rating': 4.0,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Morning Boat Ride on Ganges',
        'description': 'Glide past 84 ghats at sunrise watching rituals, cremation pyres, and ancient temples from the water.',
        'category': 'adventure',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3060,
        'longitude': 83.0124,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 5,
        'rating': 4.7,
        'popularity_score': 0.94,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '08:00',
        'is_outdoor': True,
    },
    {
        'name': 'Blue Lassi Shop',
        'description': 'Tiny cult-classic lassi stall near Manikarnika Ghat, churning creamy lassis with seasonal fruits since 1925.',
        'category': 'food',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3098,
        'longitude': 83.0118,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 1,
        'rating': 4.6,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '07:00',
        'closing_hour': '22:00',
        'is_outdoor': False,
    },
    {
        'name': 'Silk Weaving Workshop',
        'description': 'Visit local weavers creating world-famous Banarasi silk sarees using centuries-old techniques.',
        'category': 'shopping',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3180,
        'longitude': 83.0080,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 15,
        'rating': 4.3,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'BHU – Banaras Hindu University',
        'description': 'Asia\'s largest residential university with a beautiful campus, Bharat Kala Bhavan art museum, and New Vishwanath Temple.',
        'category': 'landmark',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.2677,
        'longitude': 82.9913,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '07:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Varanasi Street Food Trail',
        'description': 'Kachori-sabji, tamatar chaat, malaiyyo in winter, and the famous Banarasi paan — a full culinary adventure.',
        'category': 'food',
        'city': 'Varanasi',
        'country': 'India',
        'latitude': 25.3130,
        'longitude': 83.0100,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 3,
        'rating': 4.5,
        'popularity_score': 0.84,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },

    # ───────────── UDAIPUR (10) ─────────────
    {
        'name': 'City Palace Udaipur',
        'description': 'Palatial complex on the banks of Lake Pichola with 11 palaces, courtyards, terraces, and a museum.',
        'category': 'landmark',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5764,
        'longitude': 73.6845,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 4,
        'rating': 4.7,
        'popularity_score': 0.95,
        'image_url': '',
        'opening_hour': '09:30',
        'closing_hour': '17:30',
        'is_outdoor': False,
    },
    {
        'name': 'Lake Pichola Boat Ride',
        'description': 'Sunset boat ride on the sparkling lake with views of Jag Mandir, the Lake Palace, and the Aravalli Hills.',
        'category': 'adventure',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5711,
        'longitude': 73.6801,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 5,
        'rating': 4.8,
        'popularity_score': 0.96,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Jag Mandir Island Palace',
        'description': 'Lake island palace dating to 1551, where the young Mughal prince Shah Jahan once took refuge.',
        'category': 'landmark',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5666,
        'longitude': 73.6785,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 6,
        'rating': 4.5,
        'popularity_score': 0.84,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Saheliyon ki Bari',
        'description': 'Garden of the Maidens: a lotus-pool garden built by a Maharana for 48 women of the royal household.',
        'category': 'nature',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5883,
        'longitude': 73.6884,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 1,
        'rating': 4.3,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Fateh Sagar Lake',
        'description': 'Scenic lake surrounded by hills with Nehru Island park, boat rides, and lively evening promenade.',
        'category': 'nature',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.6003,
        'longitude': 73.6762,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.4,
        'popularity_score': 0.80,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Vintage Car Museum',
        'description': 'Stunning collection of royal classic cars including Mercedes, Rolls-Royces, and a rare 1934 Cadillac.',
        'category': 'culture',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5686,
        'longitude': 73.6565,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 3,
        'rating': 4.2,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Jagdish Temple',
        'description': 'Beautiful 17th-century carved Indo-Aryan temple dedicated to Lord Vishnu, near the City Palace.',
        'category': 'culture',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5760,
        'longitude': 73.6831,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '14:00',
        'is_outdoor': False,
    },
    {
        'name': 'Shilpgram Craft Village',
        'description': 'Living ethnography of tribal art and crafts with huts, folk dance performances, and artisan workshops.',
        'category': 'shopping',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.6010,
        'longitude': 73.6515,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 3,
        'rating': 4.1,
        'popularity_score': 0.66,
        'image_url': '',
        'opening_hour': '11:00',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },
    {
        'name': 'Ambrai Ghat Dinner',
        'description': 'Dine lakeside with City Palace and Jag Mandir lit up across the water — Udaipur\'s most romantic setting.',
        'category': 'food',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5739,
        'longitude': 73.6802,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 10,
        'rating': 4.6,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '12:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Monsoon Palace (Sajjangarh)',
        'description': 'Hill-top palace offering breathtaking panoramic sunset views of Udaipur, its lakes, and the Aravallis.',
        'category': 'landmark',
        'city': 'Udaipur',
        'country': 'India',
        'latitude': 24.5784,
        'longitude': 73.6442,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.3,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },

    # ───────────── KOCHI (10) ─────────────
    {
        'name': 'Fort Kochi Heritage Walk',
        'description': 'Colonial streets with Dutch, Portuguese, and British architecture — spice warehouses, art galleries, and cafés.',
        'category': 'landmark',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9639,
        'longitude': 76.2426,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 0,
        'rating': 4.5,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Chinese Fishing Nets',
        'description': 'Iconic cantilevered fishing nets of Fort Kochi, used since the 14th century — best at sunset.',
        'category': 'landmark',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9668,
        'longitude': 76.2361,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },
    {
        'name': 'Alleppey Backwater Cruise',
        'description': 'Dreamy houseboat cruise through Kerala\'s famed palm-fringed backwaters, villages, and paddy fields.',
        'category': 'adventure',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.4981,
        'longitude': 76.3388,
        'avg_duration_minutes': 240,
        'avg_cost_usd': 25,
        'rating': 4.8,
        'popularity_score': 0.95,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Mattancherry Palace (Dutch Palace)',
        'description': '16th-century palace showcasing spectacular Kerala murals depicting scenes from the Ramayana.',
        'category': 'culture',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9584,
        'longitude': 76.2588,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 1,
        'rating': 4.2,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Paradesi Synagogue',
        'description': 'The oldest active synagogue in the Commonwealth (1568) with hand-painted Chinese tiles and Belgian chandeliers.',
        'category': 'culture',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9576,
        'longitude': 76.2599,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 1,
        'rating': 4.3,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '13:00',
        'is_outdoor': False,
    },
    {
        'name': 'Kerala Sadya at Grand Hotel',
        'description': 'Traditional 28-dish vegetarian feast served on a banana leaf — the ultimate Kerala dining experience.',
        'category': 'food',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9745,
        'longitude': 76.2875,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 5,
        'rating': 4.5,
        'popularity_score': 0.84,
        'image_url': '',
        'opening_hour': '12:00',
        'closing_hour': '15:00',
        'is_outdoor': False,
    },
    {
        'name': 'Marine Drive Kochi',
        'description': 'Scenic waterfront promenade with cool breezes, boat jetties, and sparkling lights after dark.',
        'category': 'relaxation',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9726,
        'longitude': 76.2780,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.3,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Spice Market (Jew Town)',
        'description': 'Aromatic lanes near the synagogue overflowing with pepper, cardamom, cinnamon, and fresh vanilla.',
        'category': 'shopping',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9579,
        'longitude': 76.2594,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 8,
        'rating': 4.2,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Cherai Beach',
        'description': 'Quiet golden-sand beach on Vypin Island, great for swimming with dolphins sometimes spotted offshore.',
        'category': 'relaxation',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 10.1406,
        'longitude': 76.1720,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },
    {
        'name': 'Kathakali Dance Show',
        'description': 'See the elaborate make-up ritual and performance of Kerala\'s classical dance-drama at Cochin Cultural Centre.',
        'category': 'culture',
        'city': 'Kochi',
        'country': 'India',
        'latitude': 9.9649,
        'longitude': 76.2434,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 4,
        'rating': 4.6,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '17:00',
        'closing_hour': '19:00',
        'is_outdoor': False,
    },

    # ───────────── AGRA (10) ─────────────
    {
        'name': 'Taj Mahal',
        'description': 'An ivory-white marble mausoleum — one of the Seven Wonders of the World, built by Shah Jahan for Mumtaz.',
        'category': 'landmark',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1751,
        'longitude': 78.0421,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 15,
        'rating': 4.9,
        'popularity_score': 0.99,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:30',
        'is_outdoor': True,
    },
    {
        'name': 'Agra Fort',
        'description': 'Massive red-sandstone UNESCO fort with palatial rooms, gardens, and a distant view of the Taj Mahal.',
        'category': 'landmark',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1795,
        'longitude': 78.0211,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 6,
        'rating': 4.7,
        'popularity_score': 0.94,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Fatehpur Sikri',
        'description': 'Abandoned 16th-century Mughal capital 37 km from Agra — stunning Buland Darwaza and Panch Mahal.',
        'category': 'landmark',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.0940,
        'longitude': 77.6614,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 5,
        'rating': 4.5,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Mehtab Bagh',
        'description': 'Charbagh garden across the Yamuna offering the most picture-perfect sunset view of the Taj Mahal.',
        'category': 'nature',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1806,
        'longitude': 78.0449,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 3,
        'rating': 4.6,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Itimad-ud-Daulah (Baby Taj)',
        'description': 'Elegant white-marble tomb predating the Taj — the first Mughal structure entirely of marble with pietra dura inlay.',
        'category': 'landmark',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1927,
        'longitude': 78.0309,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 3,
        'rating': 4.4,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Kinari Bazaar',
        'description': 'Bustling old-city market famous for marble inlay work, leather goods, and Mughal-style jewellery.',
        'category': 'shopping',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1780,
        'longitude': 78.0200,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 10,
        'rating': 4.0,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Petha at Panchhi',
        'description': 'Agra\'s famous translucent sweet made from ash gourd — try angoori, paan, and kesar flavours.',
        'category': 'food',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1760,
        'longitude': 78.0188,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 2,
        'rating': 4.3,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '22:00',
        'is_outdoor': False,
    },
    {
        'name': 'Akbar\'s Tomb, Sikandra',
        'description': 'Spacious tomb complex of Emperor Akbar featuring a blend of Hindu and Islamic architecture surrounded by deer.',
        'category': 'culture',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.2186,
        'longitude': 77.9518,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 2,
        'rating': 4.2,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Mughlai Dinner at Pinch of Spice',
        'description': 'Popular restaurant for creamy dal makhani, butter chicken, and Mughlai biryani in a relaxed setting.',
        'category': 'food',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1920,
        'longitude': 78.0025,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 6,
        'rating': 4.4,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '11:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },
    {
        'name': 'Taj Nature Walk',
        'description': 'Eco-trail along the Yamuna with butterfly gardens and several vantage points for Taj Mahal photos.',
        'category': 'nature',
        'city': 'Agra',
        'country': 'India',
        'latitude': 27.1689,
        'longitude': 78.0420,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 1,
        'rating': 4.1,
        'popularity_score': 0.64,
        'image_url': '',
        'opening_hour': '07:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },

    # ───────────── RISHIKESH (10) ─────────────
    {
        'name': 'Laxman Jhula',
        'description': 'Iconic 450-ft suspension bridge across the Ganges surrounded by ashrams, temples, and river views.',
        'category': 'landmark',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1241,
        'longitude': 78.3224,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.5,
        'popularity_score': 0.92,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Ram Jhula',
        'description': 'Parallel iron suspension bridge offering stunning views of the Ganga and the Himalayan foothills.',
        'category': 'landmark',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1116,
        'longitude': 78.3228,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Triveni Ghat Aarti',
        'description': 'Ethereal evening fire ceremony at the confluence of three rivers — a spiritual highlight of Rishikesh.',
        'category': 'culture',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1034,
        'longitude': 78.3119,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.7,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '17:30',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },
    {
        'name': 'Beatles Ashram (Chaurasi Kutia)',
        'description': 'Abandoned Maharishi Mahesh Yogi ashram where The Beatles stayed in 1968, now covered in street art.',
        'category': 'culture',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1190,
        'longitude': 78.3256,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.5,
        'popularity_score': 0.88,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '16:00',
        'is_outdoor': True,
    },
    {
        'name': 'White Water Rafting',
        'description': 'Thrilling Grade III–IV rapids on the Ganges from Shivpuri to Laxman Jhula — 16 km of pure adrenaline.',
        'category': 'adventure',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1442,
        'longitude': 78.3864,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 12,
        'rating': 4.7,
        'popularity_score': 0.94,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '15:00',
        'is_outdoor': True,
    },
    {
        'name': 'Bungee Jumping at Jumpin Heights',
        'description': 'India\'s highest bungee jump (83 metres) over a rocky gorge — certified by the NZ bungee association.',
        'category': 'adventure',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1696,
        'longitude': 78.3737,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 30,
        'rating': 4.6,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Neelkanth Mahadev Temple',
        'description': 'Ancient Shiva temple at 1,330 m in the Garhwal Himalayas, set amidst dense jungle on a scenic drive.',
        'category': 'culture',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1507,
        'longitude': 78.3933,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },
    {
        'name': 'Yoga at Parmarth Niketan',
        'description': 'One of the largest ashrams on the Ganges — drop-in yoga and meditation sessions for all levels.',
        'category': 'relaxation',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1156,
        'longitude': 78.3233,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 3,
        'rating': 4.6,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Café Culture on Beatles Café Road',
        'description': 'Laidback bohemian cafés serving Israeli food, wood-fired pizza, fresh smoothies, and live jam sessions.',
        'category': 'food',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.1230,
        'longitude': 78.3210,
        'avg_duration_minutes': 75,
        'avg_cost_usd': 4,
        'rating': 4.3,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Rajaji National Park Safari',
        'description': 'Jungle safari spotting elephants, tigers, leopards, and over 300 bird species in the Shivalik Hills.',
        'category': 'nature',
        'city': 'Rishikesh',
        'country': 'India',
        'latitude': 30.2600,
        'longitude': 78.0780,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 8,
        'rating': 4.3,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },

    # ───────────── AMRITSAR (10) ─────────────
    {
        'name': 'Golden Temple (Harmandir Sahib)',
        'description': 'The holiest Sikh gurdwara — gilded dome reflected in the Amrit Sarovar, with 24/7 free langar kitchen.',
        'category': 'landmark',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6200,
        'longitude': 74.8765,
        'avg_duration_minutes': 150,
        'avg_cost_usd': 0,
        'rating': 4.9,
        'popularity_score': 0.98,
        'image_url': '',
        'opening_hour': '02:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Jallianwala Bagh',
        'description': 'Memorial garden at the site of the 1919 massacre — bullet marks still visible on the walls.',
        'category': 'landmark',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6211,
        'longitude': 74.8803,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.6,
        'popularity_score': 0.92,
        'image_url': '',
        'opening_hour': '06:30',
        'closing_hour': '19:30',
        'is_outdoor': True,
    },
    {
        'name': 'Wagah Border Ceremony',
        'description': 'Electrifying daily flag-lowering ceremony at the India-Pakistan border with patriotic fervour.',
        'category': 'culture',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6046,
        'longitude': 74.5737,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 0,
        'rating': 4.7,
        'popularity_score': 0.94,
        'image_url': '',
        'opening_hour': '15:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Partition Museum',
        'description': 'Moving museum documenting the 1947 Partition through personal stories, photos, and artefacts.',
        'category': 'culture',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6234,
        'longitude': 74.8729,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 2,
        'rating': 4.5,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Gobindgarh Fort',
        'description': 'Restored 18th-century Sikh fort with 7D shows, Sikh artefacts, and live cultural performances.',
        'category': 'landmark',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6307,
        'longitude': 74.8658,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 4,
        'rating': 4.3,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '22:00',
        'is_outdoor': False,
    },
    {
        'name': 'Amritsari Kulcha at Kesar da Dhaba',
        'description': 'Legendary dhaba since 1916 serving iconic amritsari kulcha with spicy chole, lassi, and phirni.',
        'category': 'food',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6232,
        'longitude': 74.8738,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 3,
        'rating': 4.7,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '22:00',
        'is_outdoor': False,
    },
    {
        'name': 'Hall Bazaar',
        'description': 'Main shopping street near the Golden Temple for Phulkari embroidery, juttis, dry fruits, and Amritsari papad.',
        'category': 'shopping',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6267,
        'longitude': 74.8747,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 12,
        'rating': 4.1,
        'popularity_score': 0.74,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Ram Bagh Garden',
        'description': 'Historic garden built by Maharaja Ranjit Singh, now a museum housing Punjab-era weapons and paintings.',
        'category': 'nature',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6316,
        'longitude': 74.8694,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 1,
        'rating': 4.0,
        'popularity_score': 0.64,
        'image_url': '',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Durgiana Temple',
        'description': 'Hindu temple modelled after the Golden Temple, dedicated to Goddess Durga and Lord Lakshmi Narayan.',
        'category': 'culture',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6157,
        'longitude': 74.8801,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '06:00',
        'closing_hour': '21:00',
        'is_outdoor': False,
    },
    {
        'name': 'Amritsari Fish Fry at Makhan',
        'description': 'Crispy golden fish fry marinated in Amritsari spices — a must-try street-food experience.',
        'category': 'food',
        'city': 'Amritsar',
        'country': 'India',
        'latitude': 31.6245,
        'longitude': 74.8723,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 4,
        'rating': 4.5,
        'popularity_score': 0.80,
        'image_url': '',
        'opening_hour': '11:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },

    # ───────────── SHIMLA (10) ─────────────
    {
        'name': 'The Ridge',
        'description': 'Heart of Shimla — large open space with views of surrounding mountains, the Christ Church, and town activity.',
        'category': 'landmark',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1048,
        'longitude': 77.1710,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.4,
        'popularity_score': 0.90,
        'image_url': '',
        'opening_hour': '00:00',
        'closing_hour': '23:59',
        'is_outdoor': True,
    },
    {
        'name': 'Mall Road',
        'description': 'Bustling pedestrian shopping street with colonial buildings, bookshops, cafés, and panoramic valley views.',
        'category': 'shopping',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1045,
        'longitude': 77.1695,
        'avg_duration_minutes': 120,
        'avg_cost_usd': 15,
        'rating': 4.3,
        'popularity_score': 0.86,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Jakhoo Temple',
        'description': 'Hilltop Hanuman temple at 2,455 m with a 108-ft statue and panoramic Himalayan views on clear days.',
        'category': 'culture',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1121,
        'longitude': 77.1775,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 0,
        'rating': 4.3,
        'popularity_score': 0.78,
        'image_url': '',
        'opening_hour': '05:00',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Christ Church',
        'description': 'Second-oldest church in North India (1857), neo-Gothic masterpiece with five stunning stained-glass windows.',
        'category': 'landmark',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1046,
        'longitude': 77.1716,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 0,
        'rating': 4.5,
        'popularity_score': 0.82,
        'image_url': '',
        'opening_hour': '08:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Kufri Adventure',
        'description': 'Hill station 16 km from Shimla offering horse riding, yak rides, skiing (winter) and a Himalayan zoo.',
        'category': 'adventure',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.0993,
        'longitude': 77.2645,
        'avg_duration_minutes': 180,
        'avg_cost_usd': 8,
        'rating': 4.2,
        'popularity_score': 0.80,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Kalka–Shimla Toy Train',
        'description': 'UNESCO World Heritage railway — a scenic 96-km journey through 102 tunnels and 800+ bridges.',
        'category': 'adventure',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1010,
        'longitude': 77.1690,
        'avg_duration_minutes': 300,
        'avg_cost_usd': 5,
        'rating': 4.7,
        'popularity_score': 0.92,
        'image_url': '',
        'opening_hour': '04:00',
        'closing_hour': '20:00',
        'is_outdoor': True,
    },
    {
        'name': 'Annandale',
        'description': 'Flat open ground surrounded by tall deodar trees — once the playground and racecourse of the British Raj.',
        'category': 'nature',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.0983,
        'longitude': 77.1553,
        'avg_duration_minutes': 60,
        'avg_cost_usd': 0,
        'rating': 4.0,
        'popularity_score': 0.64,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Indian Institute of Advanced Study',
        'description': 'Grand Victorian building (former Viceregal Lodge) atop Observatory Hill with beautiful heritage gardens.',
        'category': 'culture',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1047,
        'longitude': 77.1474,
        'avg_duration_minutes': 90,
        'avg_cost_usd': 1,
        'rating': 4.4,
        'popularity_score': 0.76,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Scandal Point',
        'description': 'Historic meeting spot at the junction of Ridge and Mall Road — perfect for people-watching and mountain views.',
        'category': 'relaxation',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1044,
        'longitude': 77.1700,
        'avg_duration_minutes': 30,
        'avg_cost_usd': 0,
        'rating': 4.1,
        'popularity_score': 0.72,
        'image_url': '',
        'opening_hour': '00:00',
        'closing_hour': '23:59',
        'is_outdoor': True,
    },
    {
        'name': 'Shimla Café Trail (Indian Coffee House)',
        'description': 'Historic café on the Mall Road serving filter coffee and dosa since 1957, with old-world colonial charm.',
        'category': 'food',
        'city': 'Shimla',
        'country': 'India',
        'latitude': 31.1035,
        'longitude': 77.1680,
        'avg_duration_minutes': 45,
        'avg_cost_usd': 3,
        'rating': 4.2,
        'popularity_score': 0.68,
        'image_url': '',
        'opening_hour': '09:00',
        'closing_hour': '20:00',
        'is_outdoor': False,
    },
]
