"""
Seed data for places database.
Run: python manage.py shell < seed/places.py
"""
import os
import sys
import django

# Setup Django
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from places.models import Place, PlaceMetrics
from decimal import Decimal

PLACES_DATA = [
    # === PARIS ===
    {
        'name': 'Eiffel Tower',
        'description': 'Iconic iron lattice tower on the Champ de Mars, symbol of Paris.',
        'category': 'landmark',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8584,
        'longitude': 2.2945,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('28'),
        'rating': 4.7,
        'popularity_score': 0.98,
        'image_url': 'https://images.unsplash.com/photo-1511739001486-6bfe10ce65f4?w=800',
        'opening_hour': '09:00',
        'closing_hour': '23:00',
        'is_outdoor': True,
    },
    {
        'name': 'Louvre Museum',
        'description': 'World\'s largest art museum and historic monument.',
        'category': 'culture',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8606,
        'longitude': 2.3376,
        'avg_duration_minutes': 180,
        'avg_cost_usd': Decimal('22'),
        'rating': 4.8,
        'popularity_score': 0.96,
        'image_url': 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
        'opening_hour': '09:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Montmartre & Sacré-Cœur',
        'description': 'Hilltop artists\' quarter with stunning basilica views.',
        'category': 'culture',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8867,
        'longitude': 2.3431,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.88,
        'image_url': 'https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=800',
        'opening_hour': '06:00',
        'closing_hour': '22:30',
        'is_outdoor': True,
    },
    {
        'name': 'Le Marais Food Tour',
        'description': 'Guided walking food tour through the historic Marais district.',
        'category': 'food',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8566,
        'longitude': 2.3622,
        'avg_duration_minutes': 150,
        'avg_cost_usd': Decimal('85'),
        'rating': 4.8,
        'popularity_score': 0.82,
        'image_url': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        'opening_hour': '10:00',
        'closing_hour': '14:00',
        'is_outdoor': True,
    },
    {
        'name': 'Luxembourg Gardens',
        'description': 'Beautiful formal gardens with fountains and sculptures.',
        'category': 'relaxation',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8462,
        'longitude': 2.3372,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.80,
        'image_url': 'https://images.unsplash.com/photo-1555940280-66bf87aa823d?w=800',
        'opening_hour': '07:30',
        'closing_hour': '21:00',
        'is_outdoor': True,
    },
    {
        'name': 'Musée d\'Orsay',
        'description': 'Impressionist and post-impressionist masterpieces in a former railway station.',
        'category': 'culture',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8600,
        'longitude': 2.3266,
        'avg_duration_minutes': 150,
        'avg_cost_usd': Decimal('18'),
        'rating': 4.7,
        'popularity_score': 0.90,
        'image_url': 'https://images.unsplash.com/photo-1591289009723-aef0a1a8a211?w=800',
        'opening_hour': '09:30',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Seine River Cruise',
        'description': 'Scenic evening cruise along the Seine with city views.',
        'category': 'relaxation',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8589,
        'longitude': 2.2937,
        'avg_duration_minutes': 70,
        'avg_cost_usd': Decimal('18'),
        'rating': 4.5,
        'popularity_score': 0.85,
        'image_url': 'https://images.unsplash.com/photo-1460904577954-8fadb262612c?w=800',
        'opening_hour': '10:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },
    {
        'name': 'Champs-Élysées & Arc de Triomphe',
        'description': 'Famous avenue leading to the iconic triumphal arch.',
        'category': 'landmark',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8738,
        'longitude': 2.2950,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('16'),
        'rating': 4.5,
        'popularity_score': 0.92,
        'image_url': 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=800',
        'opening_hour': '10:00',
        'closing_hour': '23:00',
        'is_outdoor': True,
    },
    {
        'name': 'Café de Flore',
        'description': 'Historic Parisian café known for literary clientele.',
        'category': 'food',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8540,
        'longitude': 2.3325,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('25'),
        'rating': 4.3,
        'popularity_score': 0.75,
        'image_url': 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        'opening_hour': '07:30',
        'closing_hour': '01:30',
        'is_outdoor': False,
    },
    {
        'name': 'Notre-Dame & Île de la Cité',
        'description': 'Historic island with the famous cathedral (exterior).',
        'category': 'culture',
        'city': 'Paris',
        'country': 'France',
        'latitude': 48.8530,
        'longitude': 2.3499,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.88,
        'image_url': 'https://images.unsplash.com/photo-1478391679764-b2d8b3cd1e94?w=800',
        'opening_hour': '08:00',
        'closing_hour': '19:00',
        'is_outdoor': True,
    },

    # === TOKYO ===
    {
        'name': 'Senso-ji Temple',
        'description': 'Tokyo\'s oldest and most significant Buddhist temple.',
        'category': 'culture',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.7148,
        'longitude': 139.7967,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.92,
        'image_url': 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
        'opening_hour': '06:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Tsukiji Outer Market',
        'description': 'World-famous fish market with incredible street food.',
        'category': 'food',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6654,
        'longitude': 139.7707,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('30'),
        'rating': 4.7,
        'popularity_score': 0.90,
        'image_url': 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800',
        'opening_hour': '05:00',
        'closing_hour': '14:00',
        'is_outdoor': True,
    },
    {
        'name': 'Meiji Shrine',
        'description': 'Serene Shinto shrine surrounded by a forested park.',
        'category': 'nature',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6764,
        'longitude': 139.6993,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.7,
        'popularity_score': 0.88,
        'image_url': 'https://images.unsplash.com/photo-1583766395091-2eb9994ed094?w=800',
        'opening_hour': '05:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Shibuya Crossing',
        'description': 'The world\'s busiest pedestrian crossing.',
        'category': 'landmark',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6595,
        'longitude': 139.7004,
        'avg_duration_minutes': 45,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.4,
        'popularity_score': 0.94,
        'image_url': 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
        'is_outdoor': True,
    },
    {
        'name': 'TeamLab Borderless',
        'description': 'Immersive digital art museum with interactive installations.',
        'category': 'culture',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6259,
        'longitude': 139.7838,
        'avg_duration_minutes': 150,
        'avg_cost_usd': Decimal('32'),
        'rating': 4.8,
        'popularity_score': 0.91,
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
        'opening_hour': '10:00',
        'closing_hour': '19:00',
        'is_outdoor': False,
    },
    {
        'name': 'Shinjuku Gyoen Garden',
        'description': 'Beautiful national garden blending Japanese, French and English styles.',
        'category': 'nature',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6852,
        'longitude': 139.7100,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('5'),
        'rating': 4.6,
        'popularity_score': 0.83,
        'image_url': 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
        'opening_hour': '09:00',
        'closing_hour': '16:30',
        'is_outdoor': True,
    },
    {
        'name': 'Akihabara Electric Town',
        'description': 'Otaku culture hub with electronics, anime, and manga shops.',
        'category': 'shopping',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.7023,
        'longitude': 139.7745,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('40'),
        'rating': 4.4,
        'popularity_score': 0.86,
        'image_url': 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?w=800',
        'is_outdoor': False,
    },
    {
        'name': 'Tokyo Skytree',
        'description': 'Tallest structure in Japan with observation decks.',
        'category': 'landmark',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.7101,
        'longitude': 139.8107,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('20'),
        'rating': 4.5,
        'popularity_score': 0.87,
        'image_url': 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800',
        'opening_hour': '10:00',
        'closing_hour': '21:00',
        'is_outdoor': False,
    },
    {
        'name': 'Ramen Street (Tokyo Station)',
        'description': 'Underground corridor featuring Japan\'s best ramen shops.',
        'category': 'food',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6812,
        'longitude': 139.7671,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('15'),
        'rating': 4.5,
        'popularity_score': 0.79,
        'image_url': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
        'opening_hour': '11:00',
        'closing_hour': '23:00',
        'is_outdoor': False,
    },
    {
        'name': 'Harajuku Takeshita Street',
        'description': 'Colorful youth fashion and street food destination.',
        'category': 'shopping',
        'city': 'Tokyo',
        'country': 'Japan',
        'latitude': 35.6702,
        'longitude': 139.7026,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('25'),
        'rating': 4.3,
        'popularity_score': 0.85,
        'image_url': 'https://images.unsplash.com/photo-1532236204992-f5e85c024202?w=800',
        'is_outdoor': True,
    },

    # === NEW YORK ===
    {
        'name': 'Central Park',
        'description': 'Sprawling urban park with gardens, lakes, and performance spaces.',
        'category': 'nature',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7829,
        'longitude': -73.9654,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.8,
        'popularity_score': 0.97,
        'image_url': 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
        'opening_hour': '06:00',
        'closing_hour': '01:00',
        'is_outdoor': True,
    },
    {
        'name': 'Metropolitan Museum of Art',
        'description': 'One of the world\'s greatest art museums.',
        'category': 'culture',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7794,
        'longitude': -73.9632,
        'avg_duration_minutes': 180,
        'avg_cost_usd': Decimal('30'),
        'rating': 4.8,
        'popularity_score': 0.93,
        'image_url': 'https://images.unsplash.com/photo-1575505586569-646b2ca898fc?w=800',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Times Square',
        'description': 'Iconic commercial intersection and entertainment hub.',
        'category': 'landmark',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7580,
        'longitude': -73.9855,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.3,
        'popularity_score': 0.95,
        'image_url': 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
        'is_outdoor': True,
    },
    {
        'name': 'Brooklyn Bridge Walk',
        'description': 'Walk across the iconic bridge with Manhattan skyline views.',
        'category': 'adventure',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7061,
        'longitude': -73.9969,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.7,
        'popularity_score': 0.89,
        'image_url': 'https://images.unsplash.com/photo-1496588152823-86ff7695e68f?w=800',
        'is_outdoor': True,
    },
    {
        'name': 'Chelsea Market & High Line',
        'description': 'Foodie paradise with rooftop urban park walkway.',
        'category': 'food',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7424,
        'longitude': -74.0061,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('35'),
        'rating': 4.6,
        'popularity_score': 0.86,
        'image_url': 'https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800',
        'opening_hour': '07:00',
        'closing_hour': '21:00',
        'is_outdoor': False,
    },
    {
        'name': 'Statue of Liberty & Ellis Island',
        'description': 'America\'s beloved symbol of freedom.',
        'category': 'landmark',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.6892,
        'longitude': -74.0445,
        'avg_duration_minutes': 240,
        'avg_cost_usd': Decimal('24'),
        'rating': 4.7,
        'popularity_score': 0.91,
        'image_url': 'https://images.unsplash.com/photo-1485738422979-f5c462d49f04?w=800',
        'opening_hour': '09:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Top of the Rock',
        'description': 'Observation deck with panoramic city views.',
        'category': 'landmark',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7593,
        'longitude': -73.9794,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('40'),
        'rating': 4.7,
        'popularity_score': 0.88,
        'image_url': 'https://images.unsplash.com/photo-1490644658840-3f2e3f8c5625?w=800',
        'opening_hour': '09:00',
        'closing_hour': '23:00',
        'is_outdoor': True,
    },
    {
        'name': 'DUMBO Brooklyn',
        'description': 'Trendy waterfront neighborhood with art galleries and restaurants.',
        'category': 'culture',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7033,
        'longitude': -73.9894,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('20'),
        'rating': 4.5,
        'popularity_score': 0.81,
        'image_url': 'https://images.unsplash.com/photo-1555109307-f7d9da25c244?w=800',
        'is_outdoor': True,
    },
    {
        'name': 'Joe\'s Pizza',
        'description': 'Legendary New York-style pizza since 1975.',
        'category': 'food',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7305,
        'longitude': -74.0002,
        'avg_duration_minutes': 30,
        'avg_cost_usd': Decimal('8'),
        'rating': 4.5,
        'popularity_score': 0.78,
        'image_url': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
        'opening_hour': '10:00',
        'closing_hour': '04:00',
        'is_outdoor': False,
    },
    {
        'name': 'The High Line',
        'description': 'Elevated linear park on a former rail line.',
        'category': 'nature',
        'city': 'New York',
        'country': 'USA',
        'latitude': 40.7480,
        'longitude': -74.0048,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.7,
        'popularity_score': 0.87,
        'image_url': 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800',
        'opening_hour': '07:00',
        'closing_hour': '22:00',
        'is_outdoor': True,
    },

    # === LONDON ===
    {
        'name': 'British Museum',
        'description': 'World-class museum of human history and culture.',
        'category': 'culture',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5194,
        'longitude': -0.1270,
        'avg_duration_minutes': 180,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.7,
        'popularity_score': 0.94,
        'image_url': 'https://images.unsplash.com/photo-1590080876351-941da357b7ae?w=800',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': False,
    },
    {
        'name': 'Tower of London',
        'description': 'Historic fortress housing the Crown Jewels.',
        'category': 'culture',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5081,
        'longitude': -0.0759,
        'avg_duration_minutes': 150,
        'avg_cost_usd': Decimal('35'),
        'rating': 4.7,
        'popularity_score': 0.91,
        'image_url': 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=800',
        'opening_hour': '09:00',
        'closing_hour': '17:30',
        'is_outdoor': True,
    },
    {
        'name': 'Borough Market',
        'description': 'London\'s most renowned food market.',
        'category': 'food',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5055,
        'longitude': -0.0910,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('20'),
        'rating': 4.6,
        'popularity_score': 0.87,
        'image_url': 'https://images.unsplash.com/photo-1580913428023-02c695666d61?w=800',
        'opening_hour': '10:00',
        'closing_hour': '17:00',
        'is_outdoor': True,
    },
    {
        'name': 'Hyde Park',
        'description': 'Royal park with Serpentine Lake and Speaker\'s Corner.',
        'category': 'nature',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5073,
        'longitude': -0.1657,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.85,
        'image_url': 'https://images.unsplash.com/photo-1591089478520-3cf537b36d04?w=800',
        'opening_hour': '05:00',
        'closing_hour': '00:00',
        'is_outdoor': True,
    },
    {
        'name': 'West End Theatre',
        'description': 'World-famous theatre district for musicals and plays.',
        'category': 'culture',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5115,
        'longitude': -0.1280,
        'avg_duration_minutes': 150,
        'avg_cost_usd': Decimal('65'),
        'rating': 4.8,
        'popularity_score': 0.88,
        'image_url': 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
        'opening_hour': '14:00',
        'closing_hour': '22:00',
        'is_outdoor': False,
    },
    {
        'name': 'Sky Garden',
        'description': 'Free rooftop garden with panoramic London views.',
        'category': 'relaxation',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5113,
        'longitude': -0.0836,
        'avg_duration_minutes': 60,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.5,
        'popularity_score': 0.80,
        'image_url': 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=800',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Camden Market',
        'description': 'Eclectic market with food, fashion, and live music.',
        'category': 'shopping',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5413,
        'longitude': -0.1462,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('15'),
        'rating': 4.4,
        'popularity_score': 0.83,
        'image_url': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': True,
    },
    {
        'name': 'Buckingham Palace',
        'description': 'Official London residence of the sovereign.',
        'category': 'landmark',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5014,
        'longitude': -0.1419,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('30'),
        'rating': 4.5,
        'popularity_score': 0.92,
        'image_url': 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
        'opening_hour': '09:30',
        'closing_hour': '17:30',
        'is_outdoor': True,
    },
    {
        'name': 'Tate Modern',
        'description': 'Britain\'s national museum of modern and contemporary art.',
        'category': 'culture',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5076,
        'longitude': -0.0994,
        'avg_duration_minutes': 120,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.5,
        'popularity_score': 0.86,
        'image_url': 'https://images.unsplash.com/photo-1582921017967-79d1cb6702ee?w=800',
        'opening_hour': '10:00',
        'closing_hour': '18:00',
        'is_outdoor': False,
    },
    {
        'name': 'Thames River Walk',
        'description': 'Scenic riverside walk from Westminster to the Globe.',
        'category': 'nature',
        'city': 'London',
        'country': 'United Kingdom',
        'latitude': 51.5007,
        'longitude': -0.1246,
        'avg_duration_minutes': 90,
        'avg_cost_usd': Decimal('0'),
        'rating': 4.6,
        'popularity_score': 0.82,
        'image_url': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
        'is_outdoor': True,
    },
]


def seed():
    """Seed the database with places."""
    from seed.places_extended import EXTENDED_PLACES_DATA

    all_places = PLACES_DATA + EXTENDED_PLACES_DATA
    created = 0
    updated = 0

    for data in all_places:
        opening = data.pop('opening_hour', None)
        closing = data.pop('closing_hour', None)

        obj, was_created = Place.objects.update_or_create(
            name=data['name'],
            city=data['city'],
            defaults={
                **data,
                'opening_hour': opening,
                'closing_hour': closing,
            }
        )

        if was_created:
            # Add initial metrics
            PlaceMetrics.objects.create(
                place=obj,
                crowd_level=0.3,
                weather_score=0.8,
                risk_score=0.1,
                temperature_c=22,
                weather_condition='Clear',
            )
            created += 1
        else:
            updated += 1

    print(f"Seeded places: {created} created, {updated} updated")
    print(f"Total places in DB: {Place.objects.count()}")


if __name__ == '__main__':
    seed()
