# Generated by Django 6.0.2 on 2026-02-22 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('culture', 'Culture & Heritage'), ('nature', 'Nature & Outdoors'), ('food', 'Food & Dining'), ('adventure', 'Adventure & Sports'), ('relaxation', 'Relaxation & Wellness'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife'), ('landmark', 'Landmark')], max_length=30)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_duration_minutes', models.IntegerField(default=60)),
                ('avg_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.FloatField(default=4.0)),
                ('popularity_score', models.FloatField(default=0.5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('opening_hour', models.TimeField(blank=True, null=True)),
                ('closing_hour', models.TimeField(blank=True, null=True)),
                ('is_outdoor', models.BooleanField(default=False)),
                ('accessibility_score', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['city', 'category'], name='places_city_a0be57_idx'), models.Index(fields=['latitude', 'longitude'], name='places_latitud_9cc1dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crowd_level', models.FloatField(default=0.5, help_text='0=empty, 1=packed')),
                ('weather_score', models.FloatField(default=0.8, help_text='0=terrible, 1=perfect')),
                ('risk_score', models.FloatField(default=0.0, help_text='0=safe, 1=dangerous')),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='places.place')),
            ],
            options={
                'db_table': 'place_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['place', '-timestamp'], name='place_metri_place_i_942683_idx')],
            },
        ),
    ]
