# Generated by Django 6.0.2 on 2026-02-22 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('weather', 'Weather Alert'), ('traffic', 'Traffic Disruption'), ('closure', 'Venue Closure'), ('user', 'User Request'), ('schedule', 'Scheduled Check')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField()),
                ('affected_items', models.JSONField(default=list, help_text='List of affected item IDs')),
                ('original_plan', models.JSONField(default=dict)),
                ('new_plan', models.JSONField(default=dict)),
                ('risk_score_before', models.FloatField(default=0.0)),
                ('risk_score_after', models.FloatField(default=0.0)),
                ('was_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'replan_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weather_cache',
            },
        ),
    ]
