# Generated by Django 6.0.2 on 2026-02-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replanevent',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replan_events', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='weathercache',
            index=models.Index(fields=['city', '-fetched_at'], name='weather_cac_city_c444b8_idx'),
        ),
        migrations.AddIndex(
            model_name='replanevent',
            index=models.Index(fields=['trip', '-created_at'], name='replan_even_trip_id_7ce20f_idx'),
        ),
    ]
