# Generated by Django 6.0.2 on 2026-02-22 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='For anonymous users', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_spent_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', max_length=20)),
                ('group_size', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('interest_culture', models.FloatField(default=0.5)),
                ('interest_nature', models.FloatField(default=0.5)),
                ('interest_food', models.FloatField(default=0.5)),
                ('interest_adventure', models.FloatField(default=0.5)),
                ('interest_relaxation', models.FloatField(default=0.5)),
                ('stability_index', models.FloatField(default=1.0)),
                ('risk_exposure', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
