# Generated by Django 6.0.2 on 2026-02-23 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_city',
            field=models.CharField(blank=True, default='', help_text='City of departure', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='selected_travel_option',
            field=models.ForeignKey(blank=True, help_text='The travel option chosen by the user for this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='travel.traveloption'),
        ),
    ]
