# Generated by Django 6.0.2 on 2026-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_departure_city_trip_selected_travel_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stay_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('resort', 'Resort'), ('airbnb', 'Airbnb'), ('boutique', 'Boutique'), ('any', 'Any')], default='any', help_text='Preferred accommodation type', max_length=20),
        ),
    ]
