# Generated by Django 6.0.2 on 2026-02-23 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('trips', '0004_trip_stay_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Packing List', max_length=255)),
                ('icon', models.CharField(default='list-checks', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_checklists',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.tripchecklist')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Food & Drinks'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('activities', 'Activities & Tickets'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=30)),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_by', models.CharField(blank=True, default='', help_text='Who paid (for group trips)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='default', help_text='Card colour: default, blue, green, yellow, pink, purple', max_length=20)),
                ('pinned', models.BooleanField(default=False)),
                ('day_number', models.IntegerField(blank=True, help_text='Optional link to a specific day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_notes',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=1000)),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('place_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_photos',
                'ordering': ['day_number', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TripShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('comment', 'Can Comment'), ('edit', 'Can Edit')], default='view', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_shares',
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='places.place')),
                ('trip', models.ForeignKey(blank=True, help_text='Optionally associate with a trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_places', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_places',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place')},
            },
        ),
        migrations.CreateModel(
            name='TripCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_collaborators',
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
