# Generated by Django 6.0.2 on 2026-02-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='itinerary_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='itineraries.itineraryitem'),
        ),
    ]
